# Generated by Django 3.2.8 on 2021-10-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop_Mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlogistics',
            name='process_dept',
            field=models.CharField(choices=[('account', 'Accountant'), ('sales', 'Sales'), ('warehouse', 'Warehouse'), ('quality', 'Quality'), ('logistics', 'Logistics')], max_length=20),
        ),
    ]
