# Generated by Django 3.2.8 on 2021-10-20 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop_Mgmt', '0002_alter_productlogistics_process_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='product_stock_status',
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='App_Shop_Mgmt.productcatalog'),
        ),
    ]
