# Generated by Django 3.2.8 on 2021-10-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop_Mgmt', '0003_auto_20211020_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='product_stock_status_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_incoming_qty', models.IntegerField()),
                ('product_incoming_date', models.DateTimeField(auto_now_add=True)),
                ('product_incoming', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_incomes', to='App_Shop_Mgmt.productcatalog')),
            ],
        ),
    ]
