# Generated by Django 3.2.8 on 2021-10-20 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop_Mgmt', '0005_auto_20211020_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincoming',
            name='product_incoming_date',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='product_stock_status_date',
        ),
    ]
