# Generated by Django 3.2.8 on 2021-10-20 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Shop_Mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_job_purchase_date', models.DateTimeField(auto_now_add=True)),
                ('user_job_delivery_date', models.DateField()),
                ('user_job_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_logistics', to='App_Shop_Mgmt.productlogistics')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_product_qty', models.IntegerField()),
                ('shop_product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_products', to='App_Shop_Mgmt.productcatalog')),
                ('user_job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to='App_User_Mgmt.userjob')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=300)),
                ('user_gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10)),
                ('user_age', models.IntegerField()),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
