# Generated by Django 3.2.8 on 2021-10-20 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_User_Mgmt', '0002_alter_userjob_user_job_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjob',
            name='user_job_delivery_date',
        ),
        migrations.RemoveField(
            model_name='userjob',
            name='user_job_purchase_date',
        ),
    ]
