# Generated by Django 3.2.8 on 2021-10-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_User_Mgmt', '0004_auto_20211021_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpurchase',
            old_name='user_job_id',
            new_name='user_job',
        ),
        migrations.RenameField(
            model_name='userpurchase',
            old_name='shop_product_id',
            new_name='user_product',
        ),
    ]
