# Generated by Django 3.2.8 on 2021-10-26 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User_Mgmt', '0005_auto_20211021_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjob',
            name='user_job_delivery_date',
            field=models.DateField(default=datetime.date(2021, 11, 5)),
        ),
    ]
